[project]
name = "jczx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.136.3",
    "imagesize>=2.0.0",
    "nuitka>=2.8",
    "onnxruntime>=1.26.0",
    "opencv-contrib-python>=4.10.0.84",
    "opencv-python>=4.13.0.92",
    "paddleocr>=3.7.0",
    "paddlex[ocr,ocr-core]>=3.7.1",
    "pick>=2.6.0",
    "pyinstaller>=6.0",
    "python-bidi>=0.6.10",
    "requests>=2.34.2",
    "textual>=8.2.7",
    "uiautomator2>=3.5.2",
    "uvicorn>=0.49.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
