# Form implementation generated from reading ui file 'e:\IDE\pyththon_project\jczx_auto_script\jczx\jczx\resources\jczxUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 264)
        Form.setMinimumSize(QtCore.QSize(576, 264))
        Form.setMaximumSize(QtCore.QSize(576, 284))
        Form.setStyleSheet("QWidget {\n"
"    color: black;\n"
"    border: 1px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 2px;\n"
"    padding-left: 3px;\n"
"}\n"
"QSpinBox {\n"
"    border: 1px solid #dcdfe6;\n"
"    background-color: white;\n"
"}\n"
"QSpinBox::up-buttom {\n"
"    border: 1px;\n"
"    subcontrol-origin: border; \n"
"    subcontrol-position: top right; \n"
"    margin-bottom: 0px;\n"
"}\n"
"QSpinBox::down-buttom {\n"
"    subcontrol-origin: border; \n"
"    subcontrol-position: top right; \n"
"    border: 1px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 0px;\n"
"    padding-left: 3px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 1px solid #dcdfe6;\n"
"}\n"
"QscrollBar::sub-line:vertical {\n"
"    subcontrol-origin: margin; \n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle {\n"
"    border: none;\n"
"    background-color:rgb(180, 180, 180);\n"
"}\n"
"QScrollBar::vertical {\n"
"    width: 5px;\n"
"    background-color: #dcdfe6;\n"
"    border: 1px solid #dcdfe6;\n"
"}\n"
"QCheckBox {\n"
"    padding: 0px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 1px solid #dcdfe6;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.adb_path_label = QtWidgets.QLabel(parent=Form)
        self.adb_path_label.setGeometry(QtCore.QRect(0, 0, 71, 24))
        self.adb_path_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.adb_path_label.setIndent(-1)
        self.adb_path_label.setObjectName("adb_path_label")
        self.adb_path_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.adb_path_lineEdit.setGeometry(QtCore.QRect(70, 0, 306, 24))
        self.adb_path_lineEdit.setObjectName("adb_path_lineEdit")
        self.adb_devices_label = QtWidgets.QLabel(parent=Form)
        self.adb_devices_label.setGeometry(QtCore.QRect(0, 24, 71, 24))
        self.adb_devices_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.adb_devices_label.setIndent(-1)
        self.adb_devices_label.setObjectName("adb_devices_label")
        self.choice_adbpath_Button = QtWidgets.QPushButton(parent=Form)
        self.choice_adbpath_Button.setGeometry(QtCore.QRect(354, 0, 24, 24))
        self.choice_adbpath_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.choice_adbpath_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/files.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.choice_adbpath_Button.setIcon(icon)
        self.choice_adbpath_Button.setObjectName("choice_adbpath_Button")
        self.authername_label = QtWidgets.QLabel(parent=Form)
        self.authername_label.setEnabled(True)
        self.authername_label.setGeometry(QtCore.QRect(0, 264, 577, 20))
        self.authername_label.setStyleSheet("QLabel {\n"
"    color: rgb(200, 200, 200);\n"
"    border: 1px solid #dcdfe6;\n"
"}")
        self.authername_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.authername_label.setIndent(10)
        self.authername_label.setObjectName("authername_label")
        self.logger_Browser = QtWidgets.QTextBrowser(parent=Form)
        self.logger_Browser.setGeometry(QtCore.QRect(175, 24, 225, 241))
        self.logger_Browser.setStyleSheet("QTextBrowser {\n"
"    color: black;\n"
"    background-color:  white;\n"
"    border: 2px solid rgb(238, 238, 238);\n"
"    border-radius: 1px;\n"
"}")
        self.logger_Browser.setObjectName("logger_Browser")
        self.save_config_Button = QtWidgets.QPushButton(parent=Form)
        self.save_config_Button.setGeometry(QtCore.QRect(400, 223, 175, 42))
        self.save_config_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(226, 255, 233);\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.save_config_Button.setObjectName("save_config_Button")
        self.stop_all_task_Button = QtWidgets.QPushButton(parent=Form)
        self.stop_all_task_Button.setGeometry(QtCore.QRect(400, 181, 175, 42))
        self.stop_all_task_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 239, 239);\n"
"    color: rgb(255, 32, 36);\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.stop_all_task_Button.setObjectName("stop_all_task_Button")
        self.adb_devices_comboBox = QtWidgets.QComboBox(parent=Form)
        self.adb_devices_comboBox.setGeometry(QtCore.QRect(70, 24, 105, 24))
        self.adb_devices_comboBox.setObjectName("adb_devices_comboBox")
        self.test_button = QtWidgets.QPushButton(parent=Form)
        self.test_button.setGeometry(QtCore.QRect(220, 266, 141, 20))
        self.test_button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(226, 255, 233);\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.test_button.setObjectName("test_button")
        self.help_button = QtWidgets.QPushButton(parent=Form)
        self.help_button.setGeometry(QtCore.QRect(376, 0, 24, 24))
        self.help_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.help_button.setStyleSheet("QPushButton {\n"
"    color: rgb(168, 168, 168);\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.help_button.setObjectName("help_button")
        self.help_textBrowser = QtWidgets.QTextBrowser(parent=Form)
        self.help_textBrowser.setGeometry(QtCore.QRect(175, 24, 225, 241))
        self.help_textBrowser.setObjectName("help_textBrowser")
        self.functionALL_tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.functionALL_tabWidget.setGeometry(QtCore.QRect(0, 48, 175, 221))
        self.functionALL_tabWidget.setStyleSheet("QTabBar::tab {\n"
"    width: 43px;\n"
"    height:  24px;\n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"}")
        self.functionALL_tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.functionALL_tabWidget.setUsesScrollButtons(False)
        self.functionALL_tabWidget.setDocumentMode(False)
        self.functionALL_tabWidget.setTabsClosable(False)
        self.functionALL_tabWidget.setMovable(False)
        self.functionALL_tabWidget.setTabBarAutoHide(True)
        self.functionALL_tabWidget.setObjectName("functionALL_tabWidget")
        self.function1_tab = QtWidgets.QWidget()
        self.function1_tab.setObjectName("function1_tab")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.function1_tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 171, 191))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 166, 311))
        self.scrollAreaWidgetContents_4.setMinimumSize(QtCore.QSize(0, 311))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.function1_widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_4)
        self.function1_widget.setGeometry(QtCore.QRect(0, 0, 175, 211))
        self.function1_widget.setObjectName("function1_widget")
        self.start_spend_order_Button = QtWidgets.QPushButton(parent=self.function1_widget)
        self.start_spend_order_Button.setGeometry(QtCore.QRect(0, 0, 175, 42))
        self.start_spend_order_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_spend_order_Button.setObjectName("start_spend_order_Button")
        self.start_smallCrystal_Button = QtWidgets.QPushButton(parent=self.function1_widget)
        self.start_smallCrystal_Button.setGeometry(QtCore.QRect(0, 42, 175, 42))
        self.start_smallCrystal_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_smallCrystal_Button.setObjectName("start_smallCrystal_Button")
        self.start_smallCrystal_settings_Button = QtWidgets.QPushButton(parent=self.function1_widget)
        self.start_smallCrystal_settings_Button.setGeometry(QtCore.QRect(145, 42, 24, 42))
        self.start_smallCrystal_settings_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.start_smallCrystal_settings_Button.setIcon(icon1)
        self.start_smallCrystal_settings_Button.setObjectName("start_smallCrystal_settings_Button")
        self.start_spend_order_settings_Button = QtWidgets.QPushButton(parent=self.function1_widget)
        self.start_spend_order_settings_Button.setGeometry(QtCore.QRect(145, 0, 24, 42))
        self.start_spend_order_settings_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_spend_order_settings_Button.setIcon(icon1)
        self.start_spend_order_settings_Button.setObjectName("start_spend_order_settings_Button")
        self.start_JJCTask_settings_Button = QtWidgets.QPushButton(parent=self.function1_widget)
        self.start_JJCTask_settings_Button.setGeometry(QtCore.QRect(145, 84, 24, 42))
        self.start_JJCTask_settings_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_JJCTask_settings_Button.setIcon(icon1)
        self.start_JJCTask_settings_Button.setObjectName("start_JJCTask_settings_Button")
        self.start_JJCTask_Button = QtWidgets.QPushButton(parent=self.function1_widget)
        self.start_JJCTask_Button.setGeometry(QtCore.QRect(0, 84, 175, 42))
        self.start_JJCTask_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_JJCTask_Button.setObjectName("start_JJCTask_Button")
        self.start_JDCTask_Button = QtWidgets.QPushButton(parent=self.function1_widget)
        self.start_JDCTask_Button.setGeometry(QtCore.QRect(0, 126, 175, 42))
        self.start_JDCTask_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_JDCTask_Button.setObjectName("start_JDCTask_Button")
        self.start_spend_order_Button.raise_()
        self.start_smallCrystal_Button.raise_()
        self.start_smallCrystal_settings_Button.raise_()
        self.start_spend_order_settings_Button.raise_()
        self.start_JJCTask_Button.raise_()
        self.start_JJCTask_settings_Button.raise_()
        self.start_JDCTask_Button.raise_()
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.functionALL_tabWidget.addTab(self.function1_tab, "")
        self.function2_tab = QtWidgets.QWidget()
        self.function2_tab.setObjectName("function2_tab")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.function2_tab)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 171, 211))
        self.scrollArea_3.setMinimumSize(QtCore.QSize(0, 211))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 166, 312))
        self.scrollAreaWidgetContents_5.setMinimumSize(QtCore.QSize(0, 312))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.function2_widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_5)
        self.function2_widget.setGeometry(QtCore.QRect(0, 0, 175, 211))
        self.function2_widget.setObjectName("function2_widget")
        self.auto_agree_friend_Button = QtWidgets.QPushButton(parent=self.function2_widget)
        self.auto_agree_friend_Button.setGeometry(QtCore.QRect(0, 0, 175, 42))
        self.auto_agree_friend_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.auto_agree_friend_Button.setObjectName("auto_agree_friend_Button")
        self.brushing_surportAwards_Button = QtWidgets.QPushButton(parent=self.function2_widget)
        self.brushing_surportAwards_Button.setGeometry(QtCore.QRect(0, 42, 175, 42))
        self.brushing_surportAwards_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.brushing_surportAwards_Button.setObjectName("brushing_surportAwards_Button")
        self.only_checkSpendThisTradingPost_Button = QtWidgets.QPushButton(parent=self.function2_widget)
        self.only_checkSpendThisTradingPost_Button.setGeometry(QtCore.QRect(0, 84, 175, 42))
        self.only_checkSpendThisTradingPost_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.only_checkSpendThisTradingPost_Button.setObjectName("only_checkSpendThisTradingPost_Button")
        self.useIllusion2_favor_Button = QtWidgets.QPushButton(parent=self.function2_widget)
        self.useIllusion2_favor_Button.setGeometry(QtCore.QRect(0, 126, 175, 42))
        self.useIllusion2_favor_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.useIllusion2_favor_Button.setObjectName("useIllusion2_favor_Button")
        self.useIllusion2_favor_settings_Button = QtWidgets.QPushButton(parent=self.function2_widget)
        self.useIllusion2_favor_settings_Button.setGeometry(QtCore.QRect(145, 126, 24, 42))
        self.useIllusion2_favor_settings_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.useIllusion2_favor_settings_Button.setIcon(icon1)
        self.useIllusion2_favor_settings_Button.setObjectName("useIllusion2_favor_settings_Button")
        self.start_switch_work_Button = QtWidgets.QPushButton(parent=self.function2_widget)
        self.start_switch_work_Button.setGeometry(QtCore.QRect(0, 168, 175, 42))
        self.start_switch_work_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_switch_work_Button.setObjectName("start_switch_work_Button")
        self.start_switch_work_settings_Button = QtWidgets.QPushButton(parent=self.function2_widget)
        self.start_switch_work_settings_Button.setGeometry(QtCore.QRect(145, 168, 24, 42))
        self.start_switch_work_settings_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.start_switch_work_settings_Button.setIcon(icon1)
        self.start_switch_work_settings_Button.setObjectName("start_switch_work_settings_Button")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.functionALL_tabWidget.addTab(self.function2_tab, "")
        self.Charts_tab = QtWidgets.QWidget()
        self.Charts_tab.setObjectName("Charts_tab")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.Charts_tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 171, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setEnabled(True)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 166, 311))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 311))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.widget.setGeometry(QtCore.QRect(0, 0, 171, 341))
        self.widget.setObjectName("widget")
        self.choice_Chips_Button = QtWidgets.QPushButton(parent=self.widget)
        self.choice_Chips_Button.setGeometry(QtCore.QRect(0, 126, 175, 42))
        self.choice_Chips_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.choice_Chips_Button.setObjectName("choice_Chips_Button")
        self.ItemsEX_Button = QtWidgets.QPushButton(parent=self.widget)
        self.ItemsEX_Button.setGeometry(QtCore.QRect(0, 42, 175, 42))
        self.ItemsEX_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.ItemsEX_Button.setObjectName("ItemsEX_Button")
        self.Chips_Button = QtWidgets.QPushButton(parent=self.widget)
        self.Chips_Button.setGeometry(QtCore.QRect(0, 84, 175, 42))
        self.Chips_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.Chips_Button.setObjectName("Chips_Button")
        self.growthItems_Button = QtWidgets.QPushButton(parent=self.widget)
        self.growthItems_Button.setGeometry(QtCore.QRect(0, 0, 175, 42))
        self.growthItems_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.growthItems_Button.setObjectName("growthItems_Button")
        self.role_recommend_Button = QtWidgets.QPushButton(parent=self.widget)
        self.role_recommend_Button.setGeometry(QtCore.QRect(0, 168, 175, 42))
        self.role_recommend_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.role_recommend_Button.setObjectName("role_recommend_Button")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.functionALL_tabWidget.addTab(self.Charts_tab, "")
        self.tools_tab = QtWidgets.QWidget()
        self.tools_tab.setObjectName("tools_tab")
        self.tools_widget = QtWidgets.QWidget(parent=self.tools_tab)
        self.tools_widget.setGeometry(QtCore.QRect(0, 0, 175, 191))
        self.tools_widget.setObjectName("tools_widget")
        self.quarry_calculator_Button = QtWidgets.QPushButton(parent=self.tools_widget)
        self.quarry_calculator_Button.setGeometry(QtCore.QRect(0, 0, 175, 42))
        self.quarry_calculator_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.quarry_calculator_Button.setObjectName("quarry_calculator_Button")
        self.tasks_Button = QtWidgets.QPushButton(parent=self.tools_widget)
        self.tasks_Button.setGeometry(QtCore.QRect(0, 42, 175, 42))
        self.tasks_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.tasks_Button.setObjectName("tasks_Button")
        self.functionALL_tabWidget.addTab(self.tools_tab, "")
        self.refresh_devices_Button = QtWidgets.QPushButton(parent=Form)
        self.refresh_devices_Button.setGeometry(QtCore.QRect(159, 24, 16, 24))
        self.refresh_devices_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.refresh_devices_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.refresh_devices_Button.setIcon(icon2)
        self.refresh_devices_Button.setIconSize(QtCore.QSize(10, 10))
        self.refresh_devices_Button.setObjectName("refresh_devices_Button")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(400, 0, 171, 181))
        self.stackedWidget.setObjectName("stackedWidget")
        self.OrderListSetting = QtWidgets.QWidget()
        self.OrderListSetting.setObjectName("OrderListSetting")
        self.orderList_scrollArea = QtWidgets.QScrollArea(parent=self.OrderListSetting)
        self.orderList_scrollArea.setGeometry(QtCore.QRect(0, 0, 175, 191))
        self.orderList_scrollArea.setWidgetResizable(True)
        self.orderList_scrollArea.setObjectName("orderList_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 175, 191))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.order_exp1012w_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.order_exp1012w_checkBox.setGeometry(QtCore.QRect(0, 140, 121, 20))
        self.order_exp1012w_checkBox.setStyleSheet("QCheckBox {\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.order_exp1012w_checkBox.setShortcut("")
        self.order_exp1012w_checkBox.setCheckable(True)
        self.order_exp1012w_checkBox.setChecked(False)
        self.order_exp1012w_checkBox.setAutoRepeat(False)
        self.order_exp1012w_checkBox.setTristate(False)
        self.order_exp1012w_checkBox.setObjectName("order_exp1012w_checkBox")
        self.craft_build61_enable_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.craft_build61_enable_checkBox.setGeometry(QtCore.QRect(120, 20, 60, 20))
        self.craft_build61_enable_checkBox.setStyleSheet("QCheckBox {\n"
"    padding-left: 20px;\n"
"    border-top: 1px solid #dcdfe6;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.craft_build61_enable_checkBox.setText("")
        self.craft_build61_enable_checkBox.setTristate(False)
        self.craft_build61_enable_checkBox.setObjectName("craft_build61_enable_checkBox")
        self.craft_build162_enable_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.craft_build162_enable_checkBox.setGeometry(QtCore.QRect(120, 80, 60, 20))
        self.craft_build162_enable_checkBox.setStyleSheet("QCheckBox {\n"
"    padding-left: 20px;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.craft_build162_enable_checkBox.setText("")
        self.craft_build162_enable_checkBox.setTristate(False)
        self.craft_build162_enable_checkBox.setObjectName("craft_build162_enable_checkBox")
        self.craft_build81_enable_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.craft_build81_enable_checkBox.setGeometry(QtCore.QRect(120, 40, 60, 20))
        self.craft_build81_enable_checkBox.setStyleSheet("QCheckBox {\n"
"    padding-left: 20px;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.craft_build81_enable_checkBox.setText("")
        self.craft_build81_enable_checkBox.setTristate(False)
        self.craft_build81_enable_checkBox.setObjectName("craft_build81_enable_checkBox")
        self.order_coin1012w_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.order_coin1012w_checkBox.setGeometry(QtCore.QRect(0, 120, 121, 20))
        self.order_coin1012w_checkBox.setStyleSheet("QCheckBox {\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.order_coin1012w_checkBox.setShortcut("")
        self.order_coin1012w_checkBox.setCheckable(True)
        self.order_coin1012w_checkBox.setChecked(False)
        self.order_coin1012w_checkBox.setAutoRepeat(False)
        self.order_coin1012w_checkBox.setTristate(False)
        self.order_coin1012w_checkBox.setObjectName("order_coin1012w_checkBox")
        self.craft_coin1012w_enable_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.craft_coin1012w_enable_checkBox.setGeometry(QtCore.QRect(120, 120, 60, 20))
        self.craft_coin1012w_enable_checkBox.setStyleSheet("QCheckBox {\n"
"    padding-left: 20px;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.craft_coin1012w_enable_checkBox.setText("")
        self.craft_coin1012w_enable_checkBox.setTristate(False)
        self.craft_coin1012w_enable_checkBox.setObjectName("craft_coin1012w_enable_checkBox")
        self.order_build182_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.order_build182_checkBox.setGeometry(QtCore.QRect(0, 100, 121, 20))
        self.order_build182_checkBox.setStyleSheet("QCheckBox {\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.order_build182_checkBox.setShortcut("")
        self.order_build182_checkBox.setCheckable(True)
        self.order_build182_checkBox.setChecked(True)
        self.order_build182_checkBox.setAutoRepeat(False)
        self.order_build182_checkBox.setTristate(False)
        self.order_build182_checkBox.setObjectName("order_build182_checkBox")
        self.craft_exp1012w_enable_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.craft_exp1012w_enable_checkBox.setGeometry(QtCore.QRect(120, 140, 60, 20))
        self.craft_exp1012w_enable_checkBox.setStyleSheet("QCheckBox {\n"
"    padding-left: 20px;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.craft_exp1012w_enable_checkBox.setText("")
        self.craft_exp1012w_enable_checkBox.setTristate(False)
        self.craft_exp1012w_enable_checkBox.setObjectName("craft_exp1012w_enable_checkBox")
        self.order_build61_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.order_build61_checkBox.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.order_build61_checkBox.setStyleSheet("QCheckBox {\n"
"    border-top: 1px solid #dcdfe6;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.order_build61_checkBox.setShortcut("")
        self.order_build61_checkBox.setCheckable(True)
        self.order_build61_checkBox.setChecked(True)
        self.order_build61_checkBox.setAutoRepeat(False)
        self.order_build61_checkBox.setTristate(False)
        self.order_build61_checkBox.setObjectName("order_build61_checkBox")
        self.order_build101_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.order_build101_checkBox.setGeometry(QtCore.QRect(0, 60, 121, 20))
        self.order_build101_checkBox.setStyleSheet("QCheckBox {\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.order_build101_checkBox.setShortcut("")
        self.order_build101_checkBox.setCheckable(True)
        self.order_build101_checkBox.setChecked(False)
        self.order_build101_checkBox.setAutoRepeat(False)
        self.order_build101_checkBox.setTristate(False)
        self.order_build101_checkBox.setObjectName("order_build101_checkBox")
        self.order_build81_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.order_build81_checkBox.setGeometry(QtCore.QRect(0, 40, 121, 20))
        self.order_build81_checkBox.setStyleSheet("QCheckBox {\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.order_build81_checkBox.setShortcut("")
        self.order_build81_checkBox.setCheckable(True)
        self.order_build81_checkBox.setChecked(True)
        self.order_build81_checkBox.setAutoRepeat(False)
        self.order_build81_checkBox.setTristate(False)
        self.order_build81_checkBox.setObjectName("order_build81_checkBox")
        self.craft_build182_enable_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.craft_build182_enable_checkBox.setGeometry(QtCore.QRect(120, 100, 60, 20))
        self.craft_build182_enable_checkBox.setStyleSheet("QCheckBox {\n"
"    padding-left: 20px;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.craft_build182_enable_checkBox.setText("")
        self.craft_build182_enable_checkBox.setTristate(False)
        self.craft_build182_enable_checkBox.setObjectName("craft_build182_enable_checkBox")
        self.order_build162_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.order_build162_checkBox.setGeometry(QtCore.QRect(0, 80, 121, 20))
        self.order_build162_checkBox.setStyleSheet("QCheckBox {\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.order_build162_checkBox.setShortcut("")
        self.order_build162_checkBox.setCheckable(True)
        self.order_build162_checkBox.setChecked(True)
        self.order_build162_checkBox.setAutoRepeat(False)
        self.order_build162_checkBox.setTristate(False)
        self.order_build162_checkBox.setObjectName("order_build162_checkBox")
        self.craft_build101_enable_checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
        self.craft_build101_enable_checkBox.setGeometry(QtCore.QRect(120, 60, 60, 20))
        self.craft_build101_enable_checkBox.setStyleSheet("QCheckBox {\n"
"    padding-left: 20px;\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"}")
        self.craft_build101_enable_checkBox.setText("")
        self.craft_build101_enable_checkBox.setTristate(False)
        self.craft_build101_enable_checkBox.setObjectName("craft_build101_enable_checkBox")
        self.oder_list_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.oder_list_label.setGeometry(QtCore.QRect(0, 0, 121, 24))
        self.oder_list_label.setToolTip("")
        self.oder_list_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.oder_list_label.setIndent(-1)
        self.oder_list_label.setObjectName("oder_list_label")
        self.craft_enable_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.craft_enable_label.setGeometry(QtCore.QRect(110, 0, 60, 24))
        self.craft_enable_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.craft_enable_label.setIndent(-1)
        self.craft_enable_label.setObjectName("craft_enable_label")
        self.orderList_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.OrderListSetting)
        self.SwitchWorkSetting = QtWidgets.QWidget()
        self.SwitchWorkSetting.setObjectName("SwitchWorkSetting")
        self.quarry_time_lineEdit = QtWidgets.QLineEdit(parent=self.SwitchWorkSetting)
        self.quarry_time_lineEdit.setGeometry(QtCore.QRect(70, 0, 105, 24))
        self.quarry_time_lineEdit.setText("")
        self.quarry_time_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quarry_time_lineEdit.setObjectName("quarry_time_lineEdit")
        self.quarry_time_label = QtWidgets.QLabel(parent=self.SwitchWorkSetting)
        self.quarry_time_label.setGeometry(QtCore.QRect(0, 0, 71, 24))
        self.quarry_time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quarry_time_label.setIndent(-1)
        self.quarry_time_label.setObjectName("quarry_time_label")
        self.minute_unit_label = QtWidgets.QLabel(parent=self.SwitchWorkSetting)
        self.minute_unit_label.setGeometry(QtCore.QRect(150, 0, 25, 24))
        self.minute_unit_label.setStyleSheet("QLabel {\n"
"    border-bottom: 1px solid #dcdfe6;\n"
"    border-top: 1px solid #dcdfe6;\n"
"}")
        self.minute_unit_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minute_unit_label.setIndent(-1)
        self.minute_unit_label.setObjectName("minute_unit_label")
        self.stackedWidget.addWidget(self.SwitchWorkSetting)
        self.IllusionTaskSetting = QtWidgets.QWidget()
        self.IllusionTaskSetting.setObjectName("IllusionTaskSetting")
        self.IllusionTaskSetting_widget = QtWidgets.QWidget(parent=self.IllusionTaskSetting)
        self.IllusionTaskSetting_widget.setGeometry(QtCore.QRect(0, 0, 175, 191))
        self.IllusionTaskSetting_widget.setObjectName("IllusionTaskSetting_widget")
        self.illusionChoice_Label = QtWidgets.QLabel(parent=self.IllusionTaskSetting_widget)
        self.illusionChoice_Label.setGeometry(QtCore.QRect(0, 0, 61, 24))
        self.illusionChoice_Label.setToolTip("")
        self.illusionChoice_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.illusionChoice_Label.setIndent(-1)
        self.illusionChoice_Label.setObjectName("illusionChoice_Label")
        self.IllusionChoice_comboBox = QtWidgets.QComboBox(parent=self.IllusionTaskSetting_widget)
        self.IllusionChoice_comboBox.setGeometry(QtCore.QRect(63, 0, 111, 24))
        self.IllusionChoice_comboBox.setObjectName("IllusionChoice_comboBox")
        self.illusionChoiceTeam_Label = QtWidgets.QLabel(parent=self.IllusionTaskSetting_widget)
        self.illusionChoiceTeam_Label.setGeometry(QtCore.QRect(0, 24, 61, 24))
        self.illusionChoiceTeam_Label.setToolTip("")
        self.illusionChoiceTeam_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.illusionChoiceTeam_Label.setIndent(-1)
        self.illusionChoiceTeam_Label.setObjectName("illusionChoiceTeam_Label")
        self.IllusionChoiceTeam_comboBox = QtWidgets.QComboBox(parent=self.IllusionTaskSetting_widget)
        self.IllusionChoiceTeam_comboBox.setGeometry(QtCore.QRect(63, 24, 111, 24))
        self.IllusionChoiceTeam_comboBox.setObjectName("IllusionChoiceTeam_comboBox")
        self.stackedWidget.addWidget(self.IllusionTaskSetting)
        self.useIllusion2FavorSetting = QtWidgets.QWidget()
        self.useIllusion2FavorSetting.setObjectName("useIllusion2FavorSetting")
        self.choiceTeam_label = QtWidgets.QLabel(parent=self.useIllusion2FavorSetting)
        self.choiceTeam_label.setGeometry(QtCore.QRect(0, 0, 71, 24))
        self.choiceTeam_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.choiceTeam_label.setIndent(-1)
        self.choiceTeam_label.setObjectName("choiceTeam_label")
        self.choiceTeam_comboBox = QtWidgets.QComboBox(parent=self.useIllusion2FavorSetting)
        self.choiceTeam_comboBox.setGeometry(QtCore.QRect(70, 0, 105, 24))
        self.choiceTeam_comboBox.setObjectName("choiceTeam_comboBox")
        self.illusionTime_label = QtWidgets.QLabel(parent=self.useIllusion2FavorSetting)
        self.illusionTime_label.setGeometry(QtCore.QRect(0, 24, 71, 24))
        self.illusionTime_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.illusionTime_label.setIndent(-1)
        self.illusionTime_label.setObjectName("illusionTime_label")
        self.favor_illusionToFavor_spinBox = QtWidgets.QSpinBox(parent=self.useIllusion2FavorSetting)
        self.favor_illusionToFavor_spinBox.setGeometry(QtCore.QRect(70, 24, 105, 24))
        self.favor_illusionToFavor_spinBox.setProperty("value", 60)
        self.favor_illusionToFavor_spinBox.setObjectName("favor_illusionToFavor_spinBox")
        self.illusionTime_label_2 = QtWidgets.QLabel(parent=self.useIllusion2FavorSetting)
        self.illusionTime_label_2.setGeometry(QtCore.QRect(120, 25, 24, 22))
        self.illusionTime_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.illusionTime_label_2.setIndent(-1)
        self.illusionTime_label_2.setObjectName("illusionTime_label_2")
        self.stackedWidget.addWidget(self.useIllusion2FavorSetting)
        self.quarryCalculatorPage = QtWidgets.QWidget()
        self.quarryCalculatorPage.setObjectName("quarryCalculatorPage")
        self.quarry_position1_label = QtWidgets.QLabel(parent=self.quarryCalculatorPage)
        self.quarry_position1_label.setGeometry(QtCore.QRect(0, 0, 31, 24))
        self.quarry_position1_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quarry_position1_label.setIndent(-1)
        self.quarry_position1_label.setObjectName("quarry_position1_label")
        self.quarry_position1_comboBox = QtWidgets.QComboBox(parent=self.quarryCalculatorPage)
        self.quarry_position1_comboBox.setGeometry(QtCore.QRect(34, 0, 141, 24))
        self.quarry_position1_comboBox.setObjectName("quarry_position1_comboBox")
        self.quarry_position2_comboBox = QtWidgets.QComboBox(parent=self.quarryCalculatorPage)
        self.quarry_position2_comboBox.setGeometry(QtCore.QRect(34, 24, 141, 24))
        self.quarry_position2_comboBox.setObjectName("quarry_position2_comboBox")
        self.quarry_position2_label = QtWidgets.QLabel(parent=self.quarryCalculatorPage)
        self.quarry_position2_label.setGeometry(QtCore.QRect(0, 24, 31, 24))
        self.quarry_position2_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quarry_position2_label.setIndent(-1)
        self.quarry_position2_label.setObjectName("quarry_position2_label")
        self.quarry_position3_comboBox = QtWidgets.QComboBox(parent=self.quarryCalculatorPage)
        self.quarry_position3_comboBox.setGeometry(QtCore.QRect(34, 48, 141, 24))
        self.quarry_position3_comboBox.setObjectName("quarry_position3_comboBox")
        self.quarry_position3_label = QtWidgets.QLabel(parent=self.quarryCalculatorPage)
        self.quarry_position3_label.setGeometry(QtCore.QRect(0, 48, 31, 24))
        self.quarry_position3_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quarry_position3_label.setIndent(-1)
        self.quarry_position3_label.setObjectName("quarry_position3_label")
        self.quarry_position4_comboBox = QtWidgets.QComboBox(parent=self.quarryCalculatorPage)
        self.quarry_position4_comboBox.setGeometry(QtCore.QRect(34, 72, 141, 24))
        self.quarry_position4_comboBox.setObjectName("quarry_position4_comboBox")
        self.quarry_position4_label = QtWidgets.QLabel(parent=self.quarryCalculatorPage)
        self.quarry_position4_label.setGeometry(QtCore.QRect(0, 72, 31, 24))
        self.quarry_position4_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quarry_position4_label.setIndent(-1)
        self.quarry_position4_label.setObjectName("quarry_position4_label")
        self.quarry_position5_comboBox = QtWidgets.QComboBox(parent=self.quarryCalculatorPage)
        self.quarry_position5_comboBox.setGeometry(QtCore.QRect(34, 96, 141, 24))
        self.quarry_position5_comboBox.setObjectName("quarry_position5_comboBox")
        self.quarry_position5_label = QtWidgets.QLabel(parent=self.quarryCalculatorPage)
        self.quarry_position5_label.setGeometry(QtCore.QRect(0, 96, 31, 24))
        self.quarry_position5_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quarry_position5_label.setIndent(-1)
        self.quarry_position5_label.setObjectName("quarry_position5_label")
        self.quarry_start_operation_Button = QtWidgets.QPushButton(parent=self.quarryCalculatorPage)
        self.quarry_start_operation_Button.setGeometry(QtCore.QRect(0, 139, 175, 42))
        self.quarry_start_operation_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.quarry_start_operation_Button.setObjectName("quarry_start_operation_Button")
        self.stackedWidget.addWidget(self.quarryCalculatorPage)
        self.TaskSettingPage = QtWidgets.QWidget()
        self.TaskSettingPage.setObjectName("TaskSettingPage")
        self.choiceTask_comboBox = QtWidgets.QComboBox(parent=self.TaskSettingPage)
        self.choiceTask_comboBox.setGeometry(QtCore.QRect(70, 0, 101, 24))
        self.choiceTask_comboBox.setObjectName("choiceTask_comboBox")
        self.choiceTask_label = QtWidgets.QLabel(parent=self.TaskSettingPage)
        self.choiceTask_label.setGeometry(QtCore.QRect(0, 0, 71, 24))
        self.choiceTask_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.choiceTask_label.setIndent(-1)
        self.choiceTask_label.setObjectName("choiceTask_label")
        self.startTask_Button = QtWidgets.QPushButton(parent=self.TaskSettingPage)
        self.startTask_Button.setGeometry(QtCore.QRect(0, 139, 87, 42))
        self.startTask_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.startTask_Button.setObjectName("startTask_Button")
        self.taskInfor_scrollArea = QtWidgets.QScrollArea(parent=self.TaskSettingPage)
        self.taskInfor_scrollArea.setGeometry(QtCore.QRect(0, 28, 171, 111))
        self.taskInfor_scrollArea.setMinimumSize(QtCore.QSize(0, 71))
        self.taskInfor_scrollArea.setWidgetResizable(True)
        self.taskInfor_scrollArea.setObjectName("taskInfor_scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 171, 111))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.taskInfor_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.taskInfor_label.setGeometry(QtCore.QRect(0, 0, 171, 111))
        self.taskInfor_label.setText("")
        self.taskInfor_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.taskInfor_label.setObjectName("taskInfor_label")
        self.taskInfor_scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.TaskCreater_Button = QtWidgets.QPushButton(parent=self.TaskSettingPage)
        self.TaskCreater_Button.setGeometry(QtCore.QRect(87, 139, 87, 42))
        self.TaskCreater_Button.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"    color: #409eff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}")
        self.TaskCreater_Button.setObjectName("TaskCreater_Button")
        self.choiceTask_label.raise_()
        self.choiceTask_comboBox.raise_()
        self.startTask_Button.raise_()
        self.taskInfor_scrollArea.raise_()
        self.TaskCreater_Button.raise_()
        self.stackedWidget.addWidget(self.TaskSettingPage)
        self.JJCSettingPage = QtWidgets.QWidget()
        self.JJCSettingPage.setObjectName("JJCSettingPage")
        self.ThresholdValue_Label = QtWidgets.QLabel(parent=self.JJCSettingPage)
        self.ThresholdValue_Label.setGeometry(QtCore.QRect(0, 24, 71, 24))
        self.ThresholdValue_Label.setToolTip("")
        self.ThresholdValue_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ThresholdValue_Label.setIndent(-1)
        self.ThresholdValue_Label.setObjectName("ThresholdValue_Label")
        self.JJCSettingTips_Label = QtWidgets.QLabel(parent=self.JJCSettingPage)
        self.JJCSettingTips_Label.setGeometry(QtCore.QRect(0, 0, 181, 24))
        self.JJCSettingTips_Label.setToolTip("")
        self.JJCSettingTips_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.JJCSettingTips_Label.setIndent(-1)
        self.JJCSettingTips_Label.setObjectName("JJCSettingTips_Label")
        self.ThresholdValue_lineEdit = QtWidgets.QLineEdit(parent=self.JJCSettingPage)
        self.ThresholdValue_lineEdit.setGeometry(QtCore.QRect(70, 24, 101, 24))
        self.ThresholdValue_lineEdit.setText("")
        self.ThresholdValue_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ThresholdValue_lineEdit.setObjectName("ThresholdValue_lineEdit")
        self.stackedWidget.addWidget(self.JJCSettingPage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.adb_path_label.raise_()
        self.adb_path_lineEdit.raise_()
        self.adb_devices_label.raise_()
        self.choice_adbpath_Button.raise_()
        self.logger_Browser.raise_()
        self.save_config_Button.raise_()
        self.adb_devices_comboBox.raise_()
        self.help_button.raise_()
        self.help_textBrowser.raise_()
        self.functionALL_tabWidget.raise_()
        self.refresh_devices_Button.raise_()
        self.stackedWidget.raise_()
        self.stop_all_task_Button.raise_()
        self.authername_label.raise_()
        self.test_button.raise_()

        self.retranslateUi(Form)
        self.functionALL_tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "交错战线AutoScript"))
        self.adb_path_label.setText(_translate("Form", "ADB路径："))
        self.adb_devices_label.setText(_translate("Form", "设备列表："))
        self.choice_adbpath_Button.setToolTip(_translate("Form", "选择ADB调试程序"))
        self.authername_label.setText(_translate("Form", "Created by 思默fine"))
        self.save_config_Button.setToolTip(_translate("Form", "保存当前配置并应用"))
        self.save_config_Button.setText(_translate("Form", "保存用户配置"))
        self.stop_all_task_Button.setToolTip(_translate("Form", "停止脚本操作游戏"))
        self.stop_all_task_Button.setText(_translate("Form", "停止所有任务"))
        self.test_button.setToolTip(_translate("Form", "test"))
        self.test_button.setText(_translate("Form", "test"))
        self.help_button.setToolTip(_translate("Form", "帮助"))
        self.help_button.setText(_translate("Form", "?"))
        self.help_textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">该版本为</span><span style=\" font-weight:700; color:#0055ff;\">开发版本</span><span style=\" font-weight:700;\">，功能可能</span><span style=\" font-weight:700; color:#ff5500;\">不稳定</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">ADB路径</span><span style=\" font-size:8pt;\">：模拟器目录下的</span><span style=\" font-size:8pt; color:#ff0000;\">ADB.exe</span><span style=\" font-size:8pt;\">调试程序路径</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">设备列表</span><span style=\" font-size:8pt;\">：模拟器下的设备，默认获取第一个设备</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">矿场结算</span><span style=\" font-size:8pt;\">：矿场每</span><span style=\" font-size:8pt; color:#ff0000;\">30分钟</span><span style=\" font-size:8pt;\">结算一次矿物，值与账号注册时间有关，当没有指定设置或者为-1时，自动挂机30分钟获取时间</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">启动交付订单</span><span style=\" font-size:8pt;\">：检查订单库并交付符合条件的订单，仅</span><span style=\" font-size:8pt; color:#ff0000;\">执行一次</span><span style=\" font-size:8pt;\">，在找完符合条件的订单并合成交付后，就结束控制</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">启动换班任务</span><span style=\" font-size:8pt;\">：全天24小时运行收益最大化，给电费大佬准备的，进行矿场换班工作，无限时间运行（除非手动停止），</span><span style=\" font-size:8pt; color:#ff0000;\">高稳定性</span><span style=\" font-size:8pt;\">，在未到达矿场结算时间是脚本不操作游戏，玩家可以自由控制（注意：请先设置【</span><span style=\" font-size:8pt; color:#ff0000;\">驻员状况</span><span style=\" font-size:8pt;\">】中的矿场编队预设，需要预设两个队伍，一个主力队伍，一个替换队伍，首先让自己的</span><span style=\" font-size:8pt; color:#ff0000;\">替换队伍</span><span style=\" font-size:8pt;\">上班，再启动该模式，启动该模式时不要让自己的</span><span style=\" font-size:8pt; color:#ff0000;\">主力挖矿</span><span style=\" font-size:8pt;\">队伍上班，实际上结算时会自动让主力队伍上班，系统还是会以主力队伍进行结算，</span><span style=\" font-size:8pt; color:#ff0000;\">替换队伍</span><span style=\" font-size:8pt;\">相当于</span><span style=\" font-size:8pt; color:#ff0000;\">占位符</span><span style=\" font-size:8pt;\">）</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">虚影微晶任务</span><span style=\" font-size:8pt;\">：当每周</span><span style=\" font-size:8pt; color:#ff0000;\">微晶未满</span><span style=\" font-size:8pt;\">时，通过通关虚影来刷取微晶</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">自动同意好友申请</span><span style=\" font-size:8pt;\">：全自动同意好友申请，用于在订单群当义父时解放双手</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">为主号刷助战奖励</span><span style=\" font-size:8pt;\">：（助战奖励只有4w，蚊子腿）确保当前使用为</span><span style=\" font-size:8pt; color:#ff0000;\">小号</span><span style=\" font-size:8pt;\">，至少通过了一次</span><span style=\" font-size:8pt; color:#ff0000;\">虚影阿瑞斯</span><span style=\" font-size:8pt;\">，且小号只有主号</span><span style=\" font-size:8pt; color:#ff0000;\">一个好友</span><span style=\" font-size:8pt;\">，同时一号队伍留有</span><span style=\" font-size:8pt; color:#ff0000;\">2x2的位置</span><span style=\" font-size:8pt; color:#000000;\">。</span><span style=\" font-size:8pt;\">关于双倍助战：助战奖励分割时间为</span><span style=\" font-size:8pt; color:#ff0000;\">每天凌晨3点</span><span style=\" font-size:8pt; color:#000000;\">，在3点之前进行20次助战，3点过后进行20次助战，3点后到第二次刷助战期间主号</span><span style=\" font-size:8pt; color:#ff0000;\">不要登录</span><span style=\" font-size:8pt; color:#000000;\">，次日双倍助战奖励，白话==&gt;（主号上线前助战20次，上线后助战20次）</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">检索交付当前订单</span><span style=\" font-size:8pt; color:#000000;\">：</span><span style=\" font-size:8pt;\">仅只检索当前订单并自动交付，若</span><span style=\" font-size:8pt; color:#ff0000;\">没有</span><span style=\" font-size:8pt;\">在订单页则前往</span><span style=\" font-size:8pt; color:#ff0000;\">交易所</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">使用虚影刷取好感</span><span style=\" font-size:8pt; color:#000000;\">：通关虚影可以涨</span><span style=\" font-size:8pt; color:#ff0000;\">好感度</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">停止所有任务</span><span style=\" font-size:8pt;\">：无视所有情况，强制停止脚本任务</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffaa00;\">保存用户配置</span><span style=\" font-size:8pt;\">：使用手动修改方式并不会触发自动保存（仅ADB路径与矿场结算时间），推荐修改配置项后手动保存配置</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.start_spend_order_Button.setToolTip(_translate("Form", "<html><head/><body><p>寻找订单并交付</p><p>【自动停止】</p></body></html>"))
        self.start_spend_order_Button.setText(_translate("Form", "启动交付订单"))
        self.start_smallCrystal_Button.setToolTip(_translate("Form", "<html><head/><body><p>根据设置通关虚影来获得微晶</p><p>【自动停止】</p></body></html>"))
        self.start_smallCrystal_Button.setText(_translate("Form", "虚影微晶任务"))
        self.start_JJCTask_Button.setToolTip(_translate("Form", "<html><head/><body><p>根据设置挑战竞技场</p><p>【自动停止】</p></body></html>"))
        self.start_JJCTask_Button.setText(_translate("Form", "镜像竞技场任务"))
        self.start_JDCTask_Button.setToolTip(_translate("Form", "<html><head/><body><p>自动化挑战角斗场随机模式</p><p>【自动停止，不保证通关】</p></body></html>"))
        self.start_JDCTask_Button.setText(_translate("Form", "角斗场任务"))
        self.functionALL_tabWidget.setTabText(self.functionALL_tabWidget.indexOf(self.function1_tab), _translate("Form", "功能1"))
        self.auto_agree_friend_Button.setToolTip(_translate("Form", "<html><head/><body><p>自动同意好友申请</p><p>【手动停止】</p></body></html>"))
        self.auto_agree_friend_Button.setText(_translate("Form", "自动同意好友申请"))
        self.brushing_surportAwards_Button.setToolTip(_translate("Form", "<html><head/><body><p>为指定的主账号刷取助战奖励</p><p>【自动停止】</p></body></html>"))
        self.brushing_surportAwards_Button.setText(_translate("Form", "为主号刷助战奖励"))
        self.only_checkSpendThisTradingPost_Button.setToolTip(_translate("Form", "<html><head/><body><p>仅只检索当前订单并自动交付</p><p>【自动停止】</p></body></html>"))
        self.only_checkSpendThisTradingPost_Button.setText(_translate("Form", "检索交付当前订单"))
        self.useIllusion2_favor_Button.setToolTip(_translate("Form", "<html><head/><body><p>刷取固定次数虚影增长好感度</p><p>【自动停止】</p></body></html>"))
        self.useIllusion2_favor_Button.setText(_translate("Form", "使用虚影刷取好感"))
        self.start_switch_work_Button.setToolTip(_translate("Form", "<html><head/><body><p>进行矿场员工换班任务</p><p>【手动停止】</p></body></html>"))
        self.start_switch_work_Button.setText(_translate("Form", "启动换班任务"))
        self.functionALL_tabWidget.setTabText(self.functionALL_tabWidget.indexOf(self.function2_tab), _translate("Form", "功能2"))
        self.choice_Chips_Button.setToolTip(_translate("Form", "来源：未知"))
        self.choice_Chips_Button.setText(_translate("Form", "自选箱芯片一览"))
        self.ItemsEX_Button.setToolTip(_translate("Form", "来源：贴吧@提多米尔斯"))
        self.ItemsEX_Button.setText(_translate("Form", "养成材料掉率一览"))
        self.Chips_Button.setToolTip(_translate("Form", "来源：b站@莉莉维斯的头"))
        self.Chips_Button.setText(_translate("Form", "芯片获得途径一览"))
        self.growthItems_Button.setToolTip(_translate("Form", "来源：@思默fine"))
        self.growthItems_Button.setText(_translate("Form", "角色养成材料一览"))
        self.role_recommend_Button.setToolTip(_translate("Form", "来源：b站@莉莉维斯的头"))
        self.role_recommend_Button.setText(_translate("Form", "角色养成推荐一览"))
        self.functionALL_tabWidget.setTabText(self.functionALL_tabWidget.indexOf(self.Charts_tab), _translate("Form", "图表"))
        self.quarry_calculator_Button.setText(_translate("Form", "矿场计算器"))
        self.tasks_Button.setText(_translate("Form", "任务列表"))
        self.functionALL_tabWidget.setTabText(self.functionALL_tabWidget.indexOf(self.tools_tab), _translate("Form", "工具"))
        self.refresh_devices_Button.setToolTip(_translate("Form", "<html><head/><body><p>刷新</p></body></html>"))
        self.order_exp1012w_checkBox.setText(_translate("Form", "10换12w经验"))
        self.order_coin1012w_checkBox.setText(_translate("Form", "10换12w星币"))
        self.order_build182_checkBox.setText(_translate("Form", "18换2构建"))
        self.order_build61_checkBox.setText(_translate("Form", "6换1构建"))
        self.order_build101_checkBox.setText(_translate("Form", "10换1构建"))
        self.order_build81_checkBox.setText(_translate("Form", "8换1构建"))
        self.order_build162_checkBox.setText(_translate("Form", "16换2构建"))
        self.oder_list_label.setText(_translate("Form", " 订单列表"))
        self.craft_enable_label.setToolTip(_translate("Form", "是否启用合成"))
        self.craft_enable_label.setText(_translate("Form", "启用合成"))
        self.quarry_time_lineEdit.setToolTip(_translate("Form", "第一次矿场结算时间 会自动获取"))
        self.quarry_time_label.setText(_translate("Form", "矿场结算："))
        self.minute_unit_label.setToolTip(_translate("Form", "第一次矿场结算时间 会自动获取"))
        self.minute_unit_label.setText(_translate("Form", "M"))
        self.illusionChoice_Label.setText(_translate("Form", "虚影关卡："))
        self.illusionChoiceTeam_Label.setText(_translate("Form", "选择队伍："))
        self.choiceTeam_label.setText(_translate("Form", "选择队伍："))
        self.illusionTime_label.setText(_translate("Form", "通关虚影："))
        self.illusionTime_label_2.setText(_translate("Form", "次"))
        self.quarry_position1_label.setText(_translate("Form", "1："))
        self.quarry_position2_label.setText(_translate("Form", "2："))
        self.quarry_position3_label.setText(_translate("Form", "3："))
        self.quarry_position4_label.setText(_translate("Form", "4："))
        self.quarry_position5_label.setText(_translate("Form", "5："))
        self.quarry_start_operation_Button.setText(_translate("Form", "开始计算"))
        self.choiceTask_label.setText(_translate("Form", "选择任务："))
        self.startTask_Button.setText(_translate("Form", "启动任务"))
        self.TaskCreater_Button.setText(_translate("Form", "任务编辑器"))
        self.ThresholdValue_Label.setText(_translate("Form", "挑战阈值："))
        self.JJCSettingTips_Label.setText(_translate("Form", "仅针对+28或者+26的竞技"))
        self.ThresholdValue_lineEdit.setToolTip(_translate("Form", "高于该阈值的镜像挑战将会跳过"))
