# Form implementation generated from reading ui file 'e:\IDE\pyththon_project\jczx_auto_script\jczx\jczxQuarryCalculator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_QuarryCalculator(object):
    def setupUi(self, QuarryCalculator):
        QuarryCalculator.setObjectName("QuarryCalculator")
        QuarryCalculator.resize(401, 431)
        QuarryCalculator.setMinimumSize(QtCore.QSize(401, 431))
        QuarryCalculator.setMaximumSize(QtCore.QSize(401, 431))
        QuarryCalculator.setStyleSheet("QWidget {\n"
"    color: black;\n"
"    border: 1px;\n"
"    background-color: white;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 2px;\n"
"    padding-left: 3px;\n"
"}\n"
"QListWidget {\n"
"    border: 1px solid #dcdfe6;\n"
"}\n"
"QScrollBar::vertical {\n"
"background:transparent;\n"
"width:2px;\n"
"border:0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"background:rgb(190, 190, 190);\n"
"width:2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"background:none;\n"
"border:none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"background:none;\n"
"border:none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background:transparent;\n"
"border:none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"background:transparent;\n"
"border:none;\n"
"}")
        self.widget = QtWidgets.QWidget(parent=QuarryCalculator)
        self.widget.setGeometry(QtCore.QRect(0, 0, 401, 431))
        self.widget.setMinimumSize(QtCore.QSize(401, 431))
        self.widget.setMaximumSize(QtCore.QSize(401, 431))
        self.widget.setObjectName("widget")
        self.score_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.score_lineEdit.setGeometry(QtCore.QRect(80, 48, 80, 24))
        self.score_lineEdit.setReadOnly(True)
        self.score_lineEdit.setObjectName("score_lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 80, 24))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(240, 0, 80, 24))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(160, 0, 80, 24))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.score_label = QtWidgets.QLabel(parent=self.widget)
        self.score_label.setGeometry(QtCore.QRect(0, 48, 80, 24))
        self.score_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.score_label.setIndent(-1)
        self.score_label.setObjectName("score_label")
        self.label_1 = QtWidgets.QLabel(parent=self.widget)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 80, 24))
        self.label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(320, 0, 80, 24))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.money_label = QtWidgets.QLabel(parent=self.widget)
        self.money_label.setGeometry(QtCore.QRect(160, 48, 161, 24))
        self.money_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.money_label.setIndent(-1)
        self.money_label.setObjectName("money_label")
        self.money_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.money_lineEdit.setGeometry(QtCore.QRect(320, 48, 80, 24))
        self.money_lineEdit.setReadOnly(True)
        self.money_lineEdit.setObjectName("money_lineEdit")
        self.base_label = QtWidgets.QLabel(parent=self.widget)
        self.base_label.setGeometry(QtCore.QRect(0, 72, 80, 24))
        self.base_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_label.setIndent(-1)
        self.base_label.setObjectName("base_label")
        self.base_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.base_lineEdit.setGeometry(QtCore.QRect(80, 72, 80, 24))
        self.base_lineEdit.setReadOnly(True)
        self.base_lineEdit.setObjectName("base_lineEdit")
        self.base_store_label = QtWidgets.QLabel(parent=self.widget)
        self.base_store_label.setGeometry(QtCore.QRect(160, 72, 80, 24))
        self.base_store_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.base_store_label.setIndent(-1)
        self.base_store_label.setObjectName("base_store_label")
        self.base_store_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.base_store_lineEdit.setGeometry(QtCore.QRect(240, 72, 161, 24))
        self.base_store_lineEdit.setReadOnly(True)
        self.base_store_lineEdit.setObjectName("base_store_lineEdit")
        self.elec_label = QtWidgets.QLabel(parent=self.widget)
        self.elec_label.setGeometry(QtCore.QRect(0, 96, 80, 24))
        self.elec_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.elec_label.setIndent(-1)
        self.elec_label.setObjectName("elec_label")
        self.elec_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.elec_lineEdit.setGeometry(QtCore.QRect(80, 96, 80, 24))
        self.elec_lineEdit.setReadOnly(True)
        self.elec_lineEdit.setObjectName("elec_lineEdit")
        self.elec_store_label = QtWidgets.QLabel(parent=self.widget)
        self.elec_store_label.setGeometry(QtCore.QRect(160, 96, 80, 24))
        self.elec_store_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.elec_store_label.setIndent(-1)
        self.elec_store_label.setObjectName("elec_store_label")
        self.elec_store_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.elec_store_lineEdit.setGeometry(QtCore.QRect(240, 96, 161, 24))
        self.elec_store_lineEdit.setReadOnly(True)
        self.elec_store_lineEdit.setObjectName("elec_store_lineEdit")
        self.smelt_label = QtWidgets.QLabel(parent=self.widget)
        self.smelt_label.setGeometry(QtCore.QRect(0, 120, 80, 24))
        self.smelt_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.smelt_label.setIndent(-1)
        self.smelt_label.setObjectName("smelt_label")
        self.smelt_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.smelt_lineEdit.setGeometry(QtCore.QRect(80, 120, 80, 24))
        self.smelt_lineEdit.setReadOnly(True)
        self.smelt_lineEdit.setObjectName("smelt_lineEdit")
        self.smelt_store_label = QtWidgets.QLabel(parent=self.widget)
        self.smelt_store_label.setGeometry(QtCore.QRect(160, 120, 80, 24))
        self.smelt_store_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.smelt_store_label.setIndent(-1)
        self.smelt_store_label.setObjectName("smelt_store_label")
        self.smelt_store_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.smelt_store_lineEdit.setGeometry(QtCore.QRect(240, 120, 161, 24))
        self.smelt_store_lineEdit.setReadOnly(True)
        self.smelt_store_lineEdit.setObjectName("smelt_store_lineEdit")
        self.label_2_1 = QtWidgets.QLabel(parent=self.widget)
        self.label_2_1.setGeometry(QtCore.QRect(80, 24, 80, 24))
        self.label_2_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2_1.setObjectName("label_2_1")
        self.label_4_1 = QtWidgets.QLabel(parent=self.widget)
        self.label_4_1.setGeometry(QtCore.QRect(240, 24, 80, 24))
        self.label_4_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4_1.setObjectName("label_4_1")
        self.label_5_1 = QtWidgets.QLabel(parent=self.widget)
        self.label_5_1.setGeometry(QtCore.QRect(320, 24, 80, 24))
        self.label_5_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5_1.setObjectName("label_5_1")
        self.label_1_1 = QtWidgets.QLabel(parent=self.widget)
        self.label_1_1.setGeometry(QtCore.QRect(0, 24, 80, 24))
        self.label_1_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1_1.setObjectName("label_1_1")
        self.label_3_1 = QtWidgets.QLabel(parent=self.widget)
        self.label_3_1.setGeometry(QtCore.QRect(160, 24, 80, 24))
        self.label_3_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3_1.setObjectName("label_3_1")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 144, 401, 286))
        self.widget_2.setObjectName("widget_2")
        self.worklist_label = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label.setGeometry(QtCore.QRect(0, 0, 44, 24))
        self.worklist_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label.setIndent(-1)
        self.worklist_label.setObjectName("worklist_label")
        self.worklist_label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_2.setGeometry(QtCore.QRect(44, 0, 44, 24))
        self.worklist_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_2.setIndent(-1)
        self.worklist_label_2.setObjectName("worklist_label_2")
        self.worklist_label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_3.setGeometry(QtCore.QRect(88, 0, 44, 24))
        self.worklist_label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_3.setIndent(-1)
        self.worklist_label_3.setObjectName("worklist_label_3")
        self.worklist_label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_4.setGeometry(QtCore.QRect(132, 0, 44, 24))
        self.worklist_label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_4.setIndent(-1)
        self.worklist_label_4.setObjectName("worklist_label_4")
        self.worklist_label_5 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_5.setGeometry(QtCore.QRect(176, 0, 44, 24))
        self.worklist_label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_5.setIndent(-1)
        self.worklist_label_5.setObjectName("worklist_label_5")
        self.worklist_label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_6.setGeometry(QtCore.QRect(220, 0, 44, 24))
        self.worklist_label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_6.setIndent(-1)
        self.worklist_label_6.setObjectName("worklist_label_6")
        self.worklist_label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_7.setGeometry(QtCore.QRect(264, 0, 44, 24))
        self.worklist_label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_7.setIndent(-1)
        self.worklist_label_7.setObjectName("worklist_label_7")
        self.worklist_label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_8.setGeometry(QtCore.QRect(308, 0, 44, 24))
        self.worklist_label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_8.setIndent(-1)
        self.worklist_label_8.setObjectName("worklist_label_8")
        self.worklist_label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.worklist_label_9.setGeometry(QtCore.QRect(352, 0, 44, 24))
        self.worklist_label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worklist_label_9.setIndent(-1)
        self.worklist_label_9.setObjectName("worklist_label_9")
        self.listWidget = QtWidgets.QListWidget(parent=self.widget_2)
        self.listWidget.setGeometry(QtCore.QRect(0, 24, 401, 271))
        self.listWidget.setObjectName("listWidget")
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.score_label.raise_()
        self.label_1.raise_()
        self.label_5.raise_()
        self.money_label.raise_()
        self.score_lineEdit.raise_()
        self.money_lineEdit.raise_()
        self.base_label.raise_()
        self.base_lineEdit.raise_()
        self.base_store_label.raise_()
        self.base_store_lineEdit.raise_()
        self.elec_label.raise_()
        self.elec_lineEdit.raise_()
        self.elec_store_label.raise_()
        self.elec_store_lineEdit.raise_()
        self.smelt_label.raise_()
        self.smelt_lineEdit.raise_()
        self.smelt_store_label.raise_()
        self.smelt_store_lineEdit.raise_()
        self.label_2_1.raise_()
        self.label_4_1.raise_()
        self.label_5_1.raise_()
        self.label_1_1.raise_()
        self.label_3_1.raise_()
        self.widget_2.raise_()

        self.retranslateUi(QuarryCalculator)
        QtCore.QMetaObject.connectSlotsByName(QuarryCalculator)

    def retranslateUi(self, QuarryCalculator):
        _translate = QtCore.QCoreApplication.translate
        QuarryCalculator.setWindowTitle(_translate("QuarryCalculator", "QuarryCalculator"))
        self.label_2.setText(_translate("QuarryCalculator", "None"))
        self.label_4.setText(_translate("QuarryCalculator", "None"))
        self.label_3.setText(_translate("QuarryCalculator", "None"))
        self.score_label.setText(_translate("QuarryCalculator", "得分："))
        self.label_1.setText(_translate("QuarryCalculator", "None"))
        self.label_5.setText(_translate("QuarryCalculator", "None"))
        self.money_label.setText(_translate("QuarryCalculator", "可能星币花费："))
        self.base_label.setText(_translate("QuarryCalculator", "原型石英："))
        self.base_store_label.setText(_translate("QuarryCalculator", "容量："))
        self.elec_label.setText(_translate("QuarryCalculator", "压电石英："))
        self.elec_store_label.setText(_translate("QuarryCalculator", "容量："))
        self.smelt_label.setText(_translate("QuarryCalculator", "熔融石英："))
        self.smelt_store_label.setText(_translate("QuarryCalculator", "容量："))
        self.label_2_1.setText(_translate("QuarryCalculator", "None"))
        self.label_4_1.setText(_translate("QuarryCalculator", "None"))
        self.label_5_1.setText(_translate("QuarryCalculator", "None"))
        self.label_1_1.setText(_translate("QuarryCalculator", "None"))
        self.label_3_1.setText(_translate("QuarryCalculator", "None"))
        self.worklist_label.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">工作流程</span></p></body></html>"))
        self.worklist_label_2.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">工作时间</span></p></body></html>"))
        self.worklist_label_3.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">原型石英</span></p></body></html>"))
        self.worklist_label_4.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">压电石英</span></p></body></html>"))
        self.worklist_label_5.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">熔融石英</span></p></body></html>"))
        self.worklist_label_6.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">当前得分</span></p></body></html>"))
        self.worklist_label_7.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">原型总量</span></p></body></html>"))
        self.worklist_label_8.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">压电总量</span></p></body></html>"))
        self.worklist_label_9.setText(_translate("QuarryCalculator", "<html><head/><body><p><span style=\" font-size:7pt;\">熔融总量</span></p></body></html>"))
